# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

NETWORK = "192.168.56."

NUM_MASTER_NODE = 2
NUM_WORKER_NODE = 2
NUM_LB_NODE = 1
IP_MASTER_START= 10
IP_MASTER_LB_START= 30
IP_NODE_START= 20
IP_NODE_LB_START= 40

REQUIRED_PLUGINS = %w(vagrant-libvirt)
exit unless REQUIRED_PLUGINS.all? do |plugin|
  Vagrant.has_plugin?(plugin) || (
    puts "The #{plugin} plugin is required. Please install it with:"
    puts "$ vagrant plugin install #{plugin}"
    false
  )
end

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"
  config.vm.box_check_update = false

  (1..NUM_MASTER_NODE).each do |i|
    config.vm.define "master-#{i}" do |libvirt|
      libvirt.vm.provider "libvirt" do |spec|
        spec.cpus = 1
        spec.memory = 1024
      end
      libvirt.vm.hostname = "master-#{i}"
      libvirt.vm.network :private_network, ip: NETWORK + "#{IP_MASTER_START + i}"
      libvirt.vm.provision "post-install", type: "shell", :path => "post-install.sh" do |s|
        s.args = [NETWORK]
      end
    end
  end

  (1..NUM_LB_NODE).each do |i|
    config.vm.define "lb-#{i}" do |libvirt|
      libvirt.vm.provider "libvirt" do |spec|
        spec.cpus = 1
        spec.memory = 1024
      end
      libvirt.vm.hostname = "lb-#{i}"
      libvirt.vm.network :private_network, ip: NETWORK + "#{IP_MASTER_LB_START}"
      libvirt.vm.network :private_network, ip: NETWORK + "#{IP_NODE_LB_START}"
      libvirt.vm.provision "post-install", type: "shell", :path => "post-install.sh" do |s|
        s.args = [NETWORK]
      end
    end
  end

  (1..NUM_WORKER_NODE).each do |i|
    config.vm.define "worker-#{i}" do |libvirt|
      libvirt.vm.provider "libvirt" do |spec|
        spec.cpus = 1
        spec.memory = 1024
      end
      libvirt.vm.hostname = "worker-#{i}"
      libvirt.vm.network :private_network, ip: NETWORK + "#{IP_NODE_START + i}"
      libvirt.vm.provision "post-install", type: "shell", :path => "post-install.sh" do |s|
        s.args = [NETWORK]
      end
    end
  end

end
