---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gangway
  labels:
    app: gangway
data:
  gangway.yaml: |
    clusterName: "kubernetes-jilo"
    authorizeURL: "https://192.168.56.40:32000/auth"
    tokenURL: "https://192.168.56.40:32000/token"
    redirectURL: "http://192.168.56.40:32001/callback"
    clientID: "gangway"
    clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
    usernameClaim: "sub"
    emailClaim: "email"
    apiServerURL: https://192.168.56.30:6443
    trustedCAPath: /cacerts/ca-login.crt
    allowEmptyClientSecret: true
    scopes: ["groups", "openid", "profile", "email", "offline_access"]
---
apiVersion: v1
kind: Secret
metadata:
  name: gangway-key
  labels:
    app: gangway
type: Opaque
stringData:
  sessionkey: secretgangwaysecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gangway
  labels:
    app: gangway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gangway
  template:
    metadata:
      labels:
        app: gangway
    spec:
      containers:
        - name: gangway
          image: gcr.io/heptio-images/gangway:v3.0.0
          imagePullPolicy: Always
          command: ["gangway", "-config", "/gangway/gangway.yaml"]
          env:
            - name: GANGWAY_SESSION_SECURITY_KEY
              valueFrom:
                secretKeyRef:
                  name: gangway-key
                  key: sessionkey
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: gangway
              mountPath: /gangway/
            - name: dex-ca
              mountPath: /cacerts/
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: gangway
          configMap:
            name: gangway
        - name: dex-ca
          secret:
            secretName: dex-ca
---
apiVersion: v1
kind: Service
metadata:
  name: gangwaysvc
  labels:
    app: gangway
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32001
  selector:
    app: gangway
