---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gangway
  labels:
    app: gangway
data:
  gangway.yaml: |
    clusterName: "kubernetes-jilo"
    authorizeURL: "https://192.168.56.21:32000/auth"
    tokenURL: "https://192.168.56.21:32000/token"
    redirectURL: "http://192.168.56.21:32001/callback"
    clientID: "gangway"
    clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
    usernameClaim: "sub"
    emailClaim: "email"
    apiServerURL: https://192.168.56.30:6443
    trustedCAPath: /etc/dex/tls/tls.crt
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gangway
  labels:
    app: gangway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gangway
  template:
    metadata:
      labels:
        app: gangway
    spec:
      containers:
        - name: gangway
          image: gcr.io/heptio-images/gangway:v2.0.0
          imagePullPolicy: Always
          command: ["gangway", "-config", "/gangway/gangway.yaml"]
          env:
            - name: GANGWAY_SESSION_SECURITY_KEY
              valueFrom:
                secretKeyRef:
                  name: gangway-key
                  key: sesssionkey
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: gangway
              mountPath: /gangway/
            - name: dex-tls
              mountPath: /etc/dex/tls
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: gangway
          configMap:
            name: gangway
        - name: dex-tls
          secret:
            secretName: dex-tls
---
apiVersion: v1
kind: Service
metadata:
  name: gangwaysvc
  labels:
    app: gangway
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32001
  selector:
    app: gangway

