apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 389
      targetPort: tcp-ldap
  selector:
    app: openldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  selector:
    matchLabels:
      app: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ORGANISATION
              value: "Lab Inc."
            - name: LDAP_DOMAIN
              value: "lab.local"
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ADMIN_PASSWORD
              value: "admin"
          ports:
            - name: tcp-ldap
              containerPort: 389
          volumeMounts:
          - name: ldap-ldif
            mountPath: /ldifs/
      volumes:
      - name: ldap-ldif
        configMap:
          name: openldap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap
  labels:
    app: openldap
data:
  0-ous.ldif: |-
    dn: ou=people,dc=lab,dc=local
    ou: people
    description: All people in organisation
    objectclass: organizationalunit

    dn: ou=groups,dc=lab,dc=local
    objectClass: organizationalUnit
    ou: groups
  1-users.ldif: |-
    dn: cn=sre,ou=people,dc=lab,dc=local
    objectClass: inetOrgPerson
    sn: sre
    cn: sre
    uid: sre
    mail: sre@lab.local
    userPassword: {SSHA}RRN6AM9u0tpTEOn6oBcIt9X3BbFPKVk5

    dn: cn=dev,ou=people,dc=lab,dc=local
    objectClass: inetOrgPerson
    sn: dev
    cn: dev
    uid: dev
    mail: dev@lab.local
    userPassword: {SSHA}RRN6AM9u0tpTEOn6oBcIt9X3BbFPKVk5
  2-groups.ldif: |-
    dn: cn=sres,ou=groups,dc=lab,dc=local
    objectClass: groupOfNames
    cn: sres
    member: cn=sre,ou=people,dc=lab,dc=local

    dn: cn=devs,ou=groups,dc=lab,dc=local
    objectClass: groupOfNames
    cn: devs
    member: cn=dev,ou=people,dc=lab,dc=local
